services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - codeigniter_network
    depends_on:
      - mysql

  webserver:
    image: nginx:latest
    container_name: codeigniter_webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - codeigniter_network

  mysql:
    image: mysql:8.0
    container_name: codeigniter-mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - codeigniter_network

networks:
  codeigniter_network:
    driver: bridge
volumes:
  mysql_data:
